apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-initdb
data:
  init.sql: |
    CREATE EXTENSION IF NOT EXISTS vector;
    CREATE TABLE IF NOT EXISTS products2 (
        id SERIAL PRIMARY KEY,
        name TEXT NOT NULL,
        category TEXT NOT NULL,
        attributes TEXT NOT NULL,
        embedding_cat VECTOR(1024),
        embedding_att VECTOR(1024)
    );